apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app-container
        image: <your-docker-image> # Replace with your Docker image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
